#!/bin/bash
#
# Author: Cyril GENISSON
# Created: 29/01/2024
# Updated: 29/01/2024
#
# Nom du script: job01
# Description: 
#
sudo apt install mariadb-server &&
sudo systemctl enable --now mariadb.service
